### ISSUE TITLE
Fetching utxo on multiple addresses on bitcore-node package v8 like v4

### ISSUE THREAD

**Issue by datgrog** [bitpay/bitcore#2123] opened 2019-04-11 13:33 UTC
After looking at `api-documentation.md` + and `bitcore-node/src/routes/api/addresses` it seems like not possible to pass multiple addresses to fetch all their utxos, only one by one.

Does I miss something ? In bitcore v4 similar feature was available [/addrs/n2Q5fc4j3gquCw4KQhzvztpGqegiWbV2ds,mnbUgz3teLJx1GZKmjoJpv4Vx8xDMeEymw/utxo]() produce indeed all utxos related to multiple addresses passed in url query

Does using v8 imply creating wallet "watch-only" to achieve similar behaviour via `/api/BTC/mainnet/wallet/:pubKey/utxos`

**Comment by datgrog** [comment] 2019-04-14 12:29
If someone is interested by this, I suggest as a **one line workaround** in `src/providers/chain-state/internal/internal.ts` :

```
  private getAddressQuery(params: CSP.StreamAddressUtxosParams) {
    const { chain, network, address, args } = params;

    if (typeof address !== 'string' || !chain || !network) {
      throw 'Missing required param';
    }

    const query = { chain: chain, network: network.toLowerCase(), address: { $in: address.split(",") } } as any; // LINE EDITED HERE

    if (args.unspent) {
      query.spentHeight = { $lt: SpentHeightIndicators.minimum };
    }
    return query;
  }
```

So that you can query an array of address delimited  by a comma like so :
`/api/BTC/testnet/address/2MtLqh1goMX3mYRWYftwENVcN3B6t6sV1JH,n2w1wQYdpY9yJ8gw51sSNVrgyg4BQfy9W7/?unspent=true`

**Comment by micahriggan** [comment] 2019-04-14 13:59
Hello @datgrog, if you'd like to submit that as a pull request I'm sure we could get that merged in.

**Comment by nitsujlangston** [comment] 2019-04-14 14:27
The change to use wallets and disallow querying multiple addresses was by design and was one of the primary architectural objectives of version 8. Querying for n addresses causes n DB seeks behind the scenes, takes n times longer for a request. Not scalable. Associating utxos with a wallet results in a single indexed DB read.

**Closed by nitsujlangston** 2019-04-14 14:27 UTC

**Comment by datgrog** [comment] 2019-04-14 15:02
Hello @nitsujlangston , I understand that linking utxos to a wallet make it more effective but given your argument and for the sake of "consistency" it feels like bitcore-node module API's route just cosmetic (other routes than what the wallet actually use)? What's the point to have them if bitcore-node is only tailored for the bitcore-wallet-service module ? <br>

In my case I would like to use bitcore to retrieve utxos from an xpub or an ypub (49 derivation instead of common 44 with p2sh(p2wpkh) addresses for segwit compatible address) in best case or from addresses otherwise. Tell me if I wrong but right now seeding a wallet from an xpub is possible, from importing address one by one is also possible but from an ypub it is not possible.
Which means if I want to fetch ypub's related utxos I need either to import addresses one by one (as p2sh is correctly recognised) in a wallet or doing my one liner workaround which is not scalable.

What would you recommend ? Many thanks.

**Comment by Roo77** [comment] 2019-04-14 21:20
Ola

**Comment by robinsingh-bw** [comment] 2019-09-08 20:45
> Hello @nitsujlangston , I understand that linking utxos to a wallet make it more effective but given your argument and for the sake of "consistency" it feels like bitcore-node module API's route just cosmetic (other routes than what the wallet actually use)? What's the point to have them if bitcore-node is only tailored for the bitcore-wallet-service module ?
> 
> In my case I would like to use bitcore to retrieve utxos from an xpub or an ypub (49 derivation instead of common 44 with p2sh(p2wpkh) addresses for segwit compatible address) in best case or from addresses otherwise. Tell me if I wrong but right now seeding a wallet from an xpub is possible, from importing address one by one is also possible but from an ypub it is not possible.
> Which means if I want to fetch ypub's related utxos I need either to import addresses one by one (as p2sh is correctly recognised) in a wallet or doing my one liner workaround which is not scalable.
> 
> What would you recommend ? Many thanks.

Hi @datgrog 

Were you able to figure this out? Need to fetch transactions for x/y/zpub keys. 

Regards.
