### ISSUE TITLE
implement filterload, filteradd, filterclear, merkleblock messages in bitcore-p2p

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1030] opened 2015-02-04 16:14 UTC
See: https://en.bitcoin.it/wiki/Protocol_specification#filterload.2C_filteradd.2C_filterclear.2C_merkleblock

**Comment by braydonf** [comment] 2015-02-04 20:55
Duplicate of: https://github.com/bitpay/bitcore-p2p/issues/10

**Closed** 2015-02-04 20:56 UTC
