### ISSUE TITLE
Dockerfile doesn't work

### ISSUE THREAD

**Issue by mvayngrib** [bitpay/bitcore#1405] opened 2016-06-06 19:54 UTC
this is the error i get:

``` bash
> utf-8-validate@1.2.1 install /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:15:12)
gyp ERR! stack     at F (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:70:19)
gyp ERR! stack     at E (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:91:16
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.19-boot2docker
gyp ERR! command "/home/bitcore/.nvm/versions/node/v4.4.5/bin/node" "/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/utf-8-validate
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> bufferutil@1.2.1 install /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:15:12)
gyp ERR! stack     at F (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:70:19)
gyp ERR! stack     at E (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:91:16
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.19-boot2docker
gyp ERR! command "/home/bitcore/.nvm/versions/node/v4.4.5/bin/node" "/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bufferutil
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> zmq@2.15.3 install /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:15:12)
gyp ERR! stack     at F (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:70:19)
gyp ERR! stack     at E (/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/which.js:91:16
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.19-boot2docker
gyp ERR! command "/home/bitcore/.nvm/versions/node/v4.4.5/bin/node" "/home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bitcore/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.4.5/bin/node" "/home/bitcore/.nvm/versions/node/v4.4.5/bin/npm" "install" "bitcore" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.4.5/bin/node" "/home/bitcore/.nvm/versions/node/v4.4.5/bin/npm" "install" "bitcore" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path npm-debug.log.1195698660
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.1195698660'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.1195698660']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.1195698660' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c /bin/bash -l -c "npm install bitcore -g"' returned a non-zero code: 1
```

**Comment by braydonf** [comment] 2016-06-07 21:51
Thanks for the report, taking a look at this.

**Comment by braydonf** [comment] 2016-06-07 22:55
@mvayngrib This PR should fix the build: https://github.com/bitpay/bitcore/pull/1408

```
cd bitcore
docker build -t bitcore .
docker run -it bitcore bash
```

Would should add a test for this as part of the travis build, looks like [it's possible](https://docs.travis-ci.com/user/docker/).

**Comment by mvayngrib** [comment] 2016-06-07 23:55
@braydonf thanks! will give it a try asap

**Comment by mvayngrib** [comment] 2016-06-09 01:20
@braydonf gave it a try and ran into another issue. I added the following lines to the Dockerfile:
```
RUN /bin/bash -l -c "cd /home/bitcore && bitcore create -t testnetnode"
WORKDIR /home/bitcore/testnetnode
CMD ["/bin/bash", "-l", "-c", "bitcore start"]
```

then i run:

```bash
docker run -it -v /home/bitcore/testnetnode/data tradle/bitcore:3 # my repo/image:tag
[2016-06-09T01:14:51.431Z] info: Using config: /home/bitcore/testnetnode/bitcore-node.json
[2016-06-09T01:14:51.434Z] info: Starting bitcoind
[2016-06-09T01:14:51.440Z] info: Starting bitcoin process
```

It sits there for a few minutes and eventually says:

```bash
[2016-06-09T00:27:45.678Z] error: Failed to start services
[2016-06-09T00:27:45.680Z] error: RPCError: Bitcoin JSON-RPC: Connection Rejected: 401 Unnauthorized
    at Bitcoin._wrapRPCError (/home/bitcore/testnetnode/node_modules/bitcore-node/lib/services/bitcoind.js:416:13)
    at /home/bitcore/testnetnode/node_modules/bitcore-node/lib/services/bitcoind.js:749:28
    at IncomingMessage.<anonymous> (/home/bitcore/testnetnode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:81:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
[2016-06-09T00:27:45.692Z] info: Beginning shutdown
[2016-06-09T00:27:45.695Z] info: Stopping bitcoind
[2016-06-09T00:27:53.422Z] info: Halted
```

i realize this is using the default bitcoin.conf, but I just want to get it working first

let me know if you know what the issue is. Thanks!

**Comment by braydonf** [comment] 2016-06-09 01:28
Hmm... I'll look into that. Did you try running once `bitcore start` without creating a new node? I didn't have any problems starting that way.

**Comment by mvayngrib** [comment] 2016-06-09 01:32
yea, that works. Can i run a testnet node that way with custom services installed?

**Comment by braydonf** [comment] 2016-06-09 01:39
It's not fully supported yet, but we have an open issue to make installing custom services to the default node smoother: https://github.com/bitpay/bitcore-node/issues/345

I'm running into the same issue creating a new node, investigating what's causing it.

**Comment by mvayngrib** [comment] 2016-06-09 01:39
awesome, thanks for the help and extreme responsiveness

**Comment by braydonf** [comment] 2016-06-09 01:53
Okay, so the issue is caused by the relative path `./data` specified for the `datadir` in the `bitcore-node.json` config, expanding it into a absolute url fixes the issue. The issue was [reported earlier](https://forum.bitcore.io/t/v4-install-hangs-at-starting-bitcoind-process/900), and the fix to handle relative paths in the config (https://github.com/bitpay/bitcore-node/pull/437) has been merged already, but not yet made it into a release.

**Comment by mvayngrib** [comment] 2016-06-09 02:03
ok, for now this works:

```
...
WORKDIR /home/bitcore/testnetnode
RUN /bin/bash -l -c "npm install --save https://github.com/braydonf/bitcore-node#4d780a9"
```

thanks!

**Comment by braydonf** [comment] 2016-06-09 15:56
Okay bitcore-node@3.0.1 released that fixes the relative datadir issue, creating a node is working as expected now.

**Comment by mvayngrib** [comment] 2016-06-09 16:25
@braydonf awesome, thanks

**Closed** 2018-09-19 14:38 UTC
Labels: confirmed bug
