### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by TakeMeNL** [bitpay/bitcore#1467] opened 2017-08-25 12:58 UTC
Node 4.7.0
Bitcore 4.1.1
Bitcoind 0.14.2
```
[2017-08-25T12:56:45.583Z] error: uncaught exception: [RangeError: index out of range]
[2017-08-25T12:56:45.586Z] error: RangeError: index out of range
at checkOffset (buffer.js:696:11)
at Buffer.readUInt32LE (buffer.js:758:5)
at BufferReader.readUInt32LE (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
at Transaction.fromBufferReader (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
at Transaction.fromBuffer (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
at InsightAPI.transactionEventHandler (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/insight-api/lib/index.js:267:30)
at emitOne (events.js:77:13)
at Bitcoin.emit (events.js:169:7)
at Bitcoin._zmqTransactionHandler (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:639:10)
at null.<anonymous> (/home/bitcoin/.nvm/versions/node/v4.7.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:713:12)
[2017-08-25T12:56:45.586Z] info: Beginning shutdown
[2017-08-25T12:56:45.587Z] info: Stopping insight-ui
[2017-08-25T12:56:45.587Z] info: Stopping insight-api
[2017-08-25T12:56:45.588Z] info: Stopping web
[2017-08-25T12:56:45.588Z] info: Stopping bitcoind
[2017-08-25T12:56:46.062Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
```

**Comment by sparsecloud** [comment] 2017-11-10 15:54
Have you had any luck with this?

**Comment by TakeMeNL** [comment] 2017-11-10 19:40
I haven't had any time to test newer versions sorry :(

**Comment by sparsecloud** [comment] 2017-11-16 11:09
Curiously enough I have bitcoin core and bitcoin cash configured under different users, it's only bitcoin core that fails and this error occurs when it catches up with the latest block.

**Comment by PavelBastov** [comment] 2017-11-30 09:50
I upgraded bitcoind from 0.12 to 0.15 and now experience the same issue? Could you guys eventually resolve it or not?

**Comment by leehankyeol** [comment] 2017-12-12 12:20
I'm currently running bitcoind while using bitcore as just a wrapper, and this happens when I try to initialize raw transaction from ZeroMQ message.

### mq.js
```javascript
// subber.js
const bitcore = require('bitcore-lib')
const zmq = require('zeromq')

const sock = zmq.socket('sub')
const port = 3000

sock.subscribe('rawtx')
sock.subscribe('rawblock')

sock.connect(`tcp://127.0.0.1:${port}`)

sock.on('message', (topic, message) => {
  const topicString = topic.toString()

  console.log('received a message related to:', topicString)
  switch (topicString) {
    case 'rawtx':
      const tx = new bitcore.Transaction(message)
      console.log(tx.toJSON())
      break
  }
})
```

### Error log
```
received a message related to: rawtx
events.js:136
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1024:11)
    at Uint8Array.readUInt32LE (buffer.js:1088:5)
    at BufferReader.readUInt32LE (/Users/user/Documents/wallet-interface/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
    at Transaction.fromBufferReader (/Users/user/Documents/wallet-interface/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
    at Transaction.fromBuffer (/Users/user/Documents/wallet-interface/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at new Transaction (/Users/user/Documents/wallet-interface/node_modules/bitcore-lib/lib/transaction/transaction.js:50:12)
    at exports.Socket.sock.on (/Users/user/Documents/wallet-interface/lib/mq.js:19:18)
    at exports.Socket.emit (events.js:159:13)
    at exports.Socket.Socket._emitMessage (/Users/user/Documents/wallet-interface/node_modules/zeromq/lib/index.js:640:15)
    at exports.Socket.Socket._flushRead (/Users/user/Documents/wallet-interface/node_modules/zeromq/lib/index.js:651:10)
```

**Comment by leehankyeol** [comment] 2017-12-13 01:58
I think I had the similar issue but I was using it with a wrong default network setting.

```
bitcore.Networks.defaultNetwork = bitcore.Networks.testnet
```

By changing the default network, the issue is now gone.

**Comment by brannondorsey** [comment] 2018-02-15 15:56
Any movement with this? I'm experiencing this problem with Node.js v8.9.4 and bitcoin core v0.15.1.0-g7b57bc998f, using latest bitcore installed from npm. Anybody found a workaround?

**Comment by brannondorsey** [comment] 2018-02-15 16:26
Looks like this is a duplicate of multiple issues on this repo. The folks over at https://github.com/bitpay/insight/issues/842 seem to have found a temporary solution.

**Comment by sparsecloud** [comment] 2018-02-19 10:18
I'm new to node and bitpay but resolved this by modifying bitcore-node.json to point to a separate installation of bitcoind (0.15.1) that I installed manually.

It looks like the version installed by node was 0.12.1. This seems to contradict what you guys are saying though, sorry. I have not set the rpcserialversion either.

**Closed** 2019-03-15 23:23 UTC
